//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMINI
{
    
    // Created out of '\Userconfig.ini'
    public class Userconfig
    {
        public const string SOURCE_INI_FILE = "C:\\Users\\piatk\\Documents\\Visual Studio 2015\\Projects\\TimeSrv\\TimeSrvLib\\Userconfi" +
            "g.ini";
        public const string SERVERS = "SERVERS";
    }
}
